export const GROUP_NAME = "GROUP_NAME";
export const GROUP_DATE = "GROUP_DATE";
export const USER_NAME = "USER_NAME";
export const USER_GIFT = "USER_GIFT";

export const SWITCH_PAGE_GROUP = "SWITCH_PAGE_GROUP";
export const SWITCH_PAGE_DATE = "SWITCH_PAGE_DATE";
export const SWITCH_PAGE_USER = "SWITCH_PAGE_USER";
export const SWITCH_PAGE_GIFT = "SWITCH_PAGE_GIFT" ;
export const SWITCH_PAGE_DONE = "SWITCH_PAGE_DONE" ;

export const SET_GROUP_ID = "SET_GROUP_ID";
export const SET_USER_ID = "SET_USER_ID";

export const GROUP_NAME_ERROR = "GROUP_NAME_ERROR";
export const GROUP_DATE_ERROR = "GROUP_DATE_ERROR";
export const USER_NAME_ERROR = "USER_NAME_ERROR";
export const USER_GIFT_ERROR = "YOUR_GIFT_ERROR";

export const EDIT_PROFILE_GROUP_NAME = "EDIT_PROFILE_GROUP_NAME";
export const EDIT_PROFILE_GROUP_DATE = "EDIT_PROFILE_GROUP_DATE";
export const EDIT_PROFILE_USER_NAME = "EDIT_PROFILE_USER_NAME";
export const EDIT_PROFILE_USER_GIFT = "EDIT_PROFILE_USER_GIFT";